version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)

  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME .
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - build.sh
      #- docker tag $IMAGE_REPO_NAME ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/$IMAGE_REPO_NAME
      #- docker run $IMAGE_REPO_NAME python -m 'scripts.build_assets'
      #- docker push ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/$IMAGE_REPO_NAME

  post_build:
    commands: #>
      # aws ecs update-service --cluster hackerstash --service $IMAGE_REPO_NAME --force-new-deployment &&
      # aws ecs wait services-stable --cluster hackerstash --services $IMAGE_REPO_NAME