version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - docker login -u hackerstash -p ryrnoh-8cuFge-rubbik
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - ./bin/build.sh

  post_build:
    commands:
      - ./bin/deploy.sh
