version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)

  build:
    commands:
      - ./build.sh

  post_build:
    commands:
      - ./deploy.sh