version: '2.0'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    command: 'python wsgi.py'
    env_file:
      - '.env'
    depends_on:
      - 'db'
      - 'redis'
    volumes:
      - '.:/app'
      - '~/.aws:/root/.aws'
    restart: always

  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'hackerstash'
      POSTGRES_USER: 'hackerstash'
      POSTGRES_PASSWORD: 'hackerstash'
    volumes:
      - './tmp/postgres-data:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    volumes:
      - './tmp/redis-data:/data'