"""Add notification settings for mentions

Revision ID: 1dd329280d2b
Revises: 6177b47619c4
Create Date: 2020-08-27 10:36:22.850992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd329280d2b'
down_revision = '6177b47619c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('someone_mentions_you_in_post_or_comment_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('someone_mentions_you_in_post_or_comment_web', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_settings', 'someone_mentions_you_in_post_or_comment_web')
    op.drop_column('notifications_settings', 'someone_mentions_you_in_post_or_comment_email')
    # ### end Alembic commands ###
