"""Add extra fields to contests

Revision ID: 2839b3a2cd31
Revises: eedcef7b8bf5
Create Date: 2020-08-21 07:10:37.212035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2839b3a2cd31'
down_revision = 'eedcef7b8bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('prizes', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('contests', sa.Column('top_up', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'top_up')
    op.drop_column('contests', 'prizes')
    # ### end Alembic commands ###
