"""Add prize awarded notification setting

Revision ID: 4702d62ddf0a
Revises: 4de8b2261f0e
Create Date: 2020-08-30 09:37:40.227813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4702d62ddf0a'
down_revision = '4de8b2261f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('prize_awarded_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('prize_awarded_web', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_settings', 'prize_awarded_web')
    op.drop_column('notifications_settings', 'prize_awarded_email')
    # ### end Alembic commands ###
