"""Add payment column

Revision ID: 53bbdf0e7e31
Revises: aef8ef0861fa
Create Date: 2020-09-11 19:48:18.955535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bbdf0e7e31'
down_revision = 'aef8ef0861fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('stripe_payment_details', sa.JSON(none_as_null=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'stripe_payment_details')
    # ### end Alembic commands ###
