"""Add stripe stuff

Revision ID: 5cd5050d5635
Revises: cebb672cc146
Create Date: 2020-09-23 18:55:14.607389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd5050d5635'
down_revision = 'cebb672cc146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('members', sa.Column('stripe_payment_details', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('members', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'stripe_subscription_id')
    op.drop_column('members', 'stripe_payment_details')
    op.drop_column('members', 'stripe_customer_id')
    # ### end Alembic commands ###
