"""Add subscription id

Revision ID: aef8ef0861fa
Revises: eef6d9c2df42
Create Date: 2020-09-11 12:43:07.489444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef8ef0861fa'
down_revision = 'eef6d9c2df42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'stripe_subscription_id')
    # ### end Alembic commands ###
