"""Add max to challenge

Revision ID: d48c59b21dbb
Revises: 2839b3a2cd31
Create Date: 2020-08-24 13:57:30.838163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48c59b21dbb'
down_revision = '2839b3a2cd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('max', sa.Integer(), nullable=False))
    op.drop_column('progress_settings', 'visible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_settings', sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('challenges', 'max')
    # ### end Alembic commands ###
