"""empty message

Revision ID: e892c375547f
Revises: a73b6a69104f
Create Date: 2020-09-22 20:19:04.717077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e892c375547f'
down_revision = 'a73b6a69104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'stripe_payment_details')
    op.drop_column('members', 'stripe_subscription_id')
    op.drop_column('members', 'stripe_customer_id')
    op.add_column('projects', sa.Column('ghost', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.drop_column('projects', 'ghost')
    op.add_column('members', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('stripe_payment_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
