"""Add stripe customer id to member

Revision ID: eef6d9c2df42
Revises: a73b6a69104f
Create Date: 2020-09-11 10:59:53.230164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef6d9c2df42'
down_revision = 'a73b6a69104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'stripe_customer_id')
    # ### end Alembic commands ###
